# Generated by Django 4.2.2 on 2023-07-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('KG', 'KG'), ('USD', 'USD'), ('EU', 'EU'), ('RU', 'RU')], default='KG', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.photo'),
        ),
    ]
