# Generated by Django 4.2.2 on 2023-07-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_likes_alter_likes_is_liked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
    ]
